### ISSUE TITLE
Sfx volume not changed when type's global volume is set to zero

### ISSUE THREAD

**Issue by danishgoel** [useflashpunk/FlashPunk#100]
If the volume of an Sfx type is set to 0 using `Sfx.setVolume("type", 0)`

Then changing the volume of an Sfx of same type like this `sfxObj.volume = 0.5` , does not change the volume of the object internally

This is because the [volume setter](https://github.com/Draknek/FlashPunk/blob/master/net/flashpunk/Sfx.as#L128) does not store the internal volume if the filteredVol is not altered. See below code (with comments explaining the issue)

```
public function set volume(value:Number):void
{
    if (!_channel) return;
    if (value < 0) value = 0;
    var filteredVol:Number = value * getVolume(_type);
    if (filteredVol < 0) filteredVol = 0;

    // as the filtered volume is not changed (due to type's volume being 0)
    // this is triggered, causing the function to return
    if (_filteredVol === filteredVol) return;

    // so this line is not executed, leaving the internal volume unchanged
    _vol = value;

    _filteredVol = _transform.volume = filteredVol;
    _channel.soundTransform = _transform;
}
```

the solution would be move the `_vol = value` line above the `_filteredVol` check

**Comment by Draknek** [comment]
Good catch! Thanks.

**Comment by danishgoel** [comment]
Wow, that was fast! Thanks a lot for fixing this.
