### ISSUE TITLE
Text Anti-aliasing  through options

### ISSUE THREAD

**Issue by matt4530** [useflashpunk/FlashPunk#105]
Text.as checks for "antialiasing" in options. If its passed in as false, then it changes the settings. However, the loop below which applies other properties to the Text will catch that and throw an error.

Solution: 

```
delete options.antialiasing; 
```

add to line 113, inside the if statement.

**Comment by Draknek** [comment]
What version of FlashPunk are you using? My current version doesn't check for antialiasing anywhere, I think that must be a modification you got from somewhere.

**Comment by matt4530** [comment]
Haha, I knew I should have checked the actual source before posting. I've got a modified version for mobile publishing, so perhaps that author put it in, which I thought was pulled directly from this repo. My apologies!

That author did confirm it was a bug, so it appears he made the addition.
