### ISSUE TITLE
When Tweens are completed, the target value should be exactly the one provided

### ISSUE THREAD

**Issue by AbelToy** [useflashpunk/FlashPunk#110]
When Tweens are completed, the target value should be exactly the one provided, not the approximation the Ease function and everything returns.

So, when the Tween finishes, the value should be set to the one provided for the Tween completion.

**Comment by zachwlewis** [comment]
I agree. I believe it's currently still lerping to the last value instead of clamping to it. I'll take a look.

**Comment by zachwlewis** [comment]
After a look, I can't find a problem. I posted a topic in the developer forums.

#### http://developers.useflashpunk.net/t/tweening-appears-to-be-working-properly/344

Can you provide repro steps to show a tween not working properly?

**Comment by Draknek** [comment]
Disagree. If you pass in an easing function that goes from 0 to 1 to 0 again, the tweened parameter should finish at the same value it started at.

If one of the built-in ease functions returns ease(1) != 1 then that's a different problem that should definitely be fixed.

**Comment by AbelToy** [comment]
Works as intended, sorry, my fault :(
