### ISSUE TITLE
Global volume controls

### ISSUE THREAD

**Issue by Draknek** [useflashpunk/FlashPunk#20]
It would be nice if there were global variables to change the volume of, or mute/unmute, all sounds.

Possibly nicer again would be the ability to control subgroups separately, e.g. sound effects vs. music.

**Comment by noonat** [comment]
Yeah, I would recommend moving this into the sound effects class directly. Right now FP.volume uses SoundMixer; the problem is that is a shared Flash Player setting, so messing with volume in another SWF can sometimes affect your muted game.

**Comment by Draknek** [comment]
Huh, I'd actually forgotten that `FP.volume` even existed. Does that mean that if you set FP.volume = 0 in a game, all future SWFs you play (including videos, etc.) will be muted?

**Comment by noonat** [comment]
Well, I'm not sure: when using FP.volume, I had player reports that games kept unmuting themselves when they weren't interacting with the game. I found that these players were using other Flash sound things at the same time (e.g. playing a podcast through a Flash player, watching a video) while the game was in a background tab. I needed discrete control over the volume of different sound groups anyway, so I replaced SoundMixer and it solved it.

It could be that it was a Flash player bug, though. I just tried to duplicate this problem, by playing audio from a SWF on two different domains, and toggling mute and on and off on the two. It didn't seem to cause any problems. SoundMixer has some other global player functionality, so it wouldn't be too surprising if this were a player version specific bug.

**Comment by noonat** [comment]
I added some code for this to my fork:
https://github.com/noonat/FlashPunk/commit/8569dbe26ea1f253a3a7f67346657b3313ee6867

**Comment by Draknek** [comment]
Cool!

Can you also please change `FP.volume` and `FP.pan` so that they change all playing sounds rather than using the `SoundMixer` class?

Naming-wise, the per-type pan/volume functions should have `get` to be consistent with the `set` functions. Am tempted to go with `getVolume` and `setVolume` over `getTypeVolume` and `setTypeVolume` too.

In the `type` setter there is a possible early out if `_type == value`.

I am slightly uneasy about the use of `||=`. The terseness is nice but the style used elsewhere in FlashPunk is this:

```
if (! _typeTransforms[type]) _typeTransforms[type] = new SoundTransform();
```

Which is slightly longer but more instantly readable.

**Comment by noonat** [comment]
Haha. I thought you might object to the `||=`. :) My thought on the type\* naming was to follow the naming on the World class, but I think you are right about just calling it `getPan/Volume` and `setPan/Volume` instead. Updated version: https://github.com/noonat/FlashPunk/blob/noonat/net/flashpunk/Sfx.as 

I explicitly left FP.volume and FP.pan untouched -- my thought is that you should be able to adjust master volume without affecting any volumes for individual groups (think volume sliders in an option menu). I am comfortable using SoundMixer instead of something more complicated, given the fact that I can't duplicate the issue I spoke of, and haven't seen others encountering it on FP's forums...

**Comment by Draknek** [comment]
I was thinking that FP.volume would still be a master volume, just implemented in a different way (since we now keep track of active sounds).

But if you feel SoundMixer is safe enough then I'm happy to keep the current code.

**Comment by Draknek** [comment]
Pushed to master.
