### ISSUE TITLE
Setting an entity's type before calling the superconstructor causes issues

### ISSUE THREAD

**Issue by Draknek** [useflashpunk/FlashPunk#25]
Can't remember now what issues though.

**Comment by AbelToy** [comment]
I don't see anything wrong with the current implementation code-wise, but I haven't tested anything yet. (tested and definitely collisions aren't working. don't see the problems tho)

**Comment by noonat** [comment]
The only issue I can think of with this is a general order of operations thing:
1. class Troll extends class Monster.
2. Troll sets type = "troll" in its constructor, then calls super()
3. Monster sets type = "monster" in its constructor.

Not a lot you can do about that...

**Comment by Draknek** [comment]
So, it turns out that every time a constructor is called, object properties are set to their default values.

Fixed in commit b8616c961ef437427ea3b5cd0b30ca7057ccab37 (I hope there are no issues with type being null rather than the empty string!)

**Comment by noonat** [comment]
Oh, interesting, I completely forgot AS3 did that. Nice catch!

You could add a check to the Entity constructor:

```
if (type === null) type = "";
```
