### ISSUE TITLE
Revert some changes from Chevy's dev branch that have never been in an official release

### ISSUE THREAD

**Issue by Draknek** [useflashpunk/FlashPunk#29]
The `Entity.name` feature and the `Tween.to` alternate tweening API are things that I have never used and have no particular inclination to support.

I am heavily tempted to remove them before releasing 1.6, so that they don't have to be officially supported.

**Comment by noonat** [comment]
Entity.name is incredibly useful for level editors, for when you need entities to have properties that refer to another entity in the level. I would recommend keeping this, though I would also recommend this change for performance: https://github.com/noonat/FlashPunk/commit/1ccc3a810263951eacc4c5fcc563120a7dd547e5

**Comment by Draknek** [comment]
That makes sense, Entity.name stays.

**Comment by Draknek** [comment]
Just took a look at that commit and I don't understand why you're mapping names to an array of entities rather than just a single entity? Names should be unique to be useful anyway.

**Comment by noonat** [comment]
That's behavior that was in Chevy's version. I was tempted to remove it myself, but left it for consistency. I'm not really sure what his reasoning for it was.

**Comment by Draknek** [comment]
Rewrote it to just keep one entity per name, since there was no API to do anything with the others anyway.
