### ISSUE TITLE
Blendmode Image stuck

### ISSUE THREAD

**Issue by Sevith** [useflashpunk/FlashPunk#32]
When you apply a Blendmode to a graphic element the image resulted stuck. Also, since the frame that the Blendmode is applied, the image position is always x = FP.camera.x and y = FP.camera.y even if you move the camera. The problem seems to be present in the newest release, I've tried an older release and the same code worked fine.

**Comment by Draknek** [comment]
I can't reproduce this issue here. Can you please post some simple code which demonstrates the issue?

**Comment by Sevith** [comment]
Sorry, my fault. I didn't check the version of FP so it resulted that I've done test with 2 different version of 1.4. With 1.6 everything works fine.
