### ISSUE TITLE
Now it never makes rounded corners for outlines.

### ISSUE THREAD

**Issue by BretHudson** [useflashpunk/FlashPunk#36]
You missed part of my code, where it checks if the user wants rounded corners on their outline or not. Now it never makes the corners round for the edges. I fixed it below.

Change
else {
        _graphics.lineStyle(thick, color, alpha, false, LineScaleMode.NORMAL, null, JointStyle.MITER);
}

To
else {
    if (radius <= 0) {
    _graphics.lineStyle(thick, color, alpha, false, "normal", null, JointStyle.MITER);
    } else {
    _graphics.lineStyle(thick, color, alpha);
    }
}

And it'll all be good. :)
  -Bret Hudson

**Comment by Draknek** [comment]
I can't reproduce this at all, and want to know why you're experiencing different behaviour to me.

The following code using my current version gives one rectangle with rounded edges and one rectangle with square edges:

```
Draw.rectPlus(10, 10, 100, 100, 0xFF0000, 0.7, false, 10.0, 15.0);
Draw.rectPlus(130, 10, 100, 100, 0xFF0000, 0.7, false, 10.0);
```

Can you post a screenshot of the result you get please?

**Comment by BretHudson** [comment]
Nevermind, it works now. :S It didn't last time I tried... weird...

Forget I said anything. :<
