### ISSUE TITLE
Fix draw hitbox of parallax entity

### ISSUE THREAD

**Issue by tmh** [useflashpunk/FlashPunk#43]
Open

<pre>
package net.flashpunk.utils.Draw
</pre>

Find in static function hitbox

<pre>
var x:int=e.x - e.originX - _camera.x, 
    y:int=e.y - e.originY - _camera.y;
</pre>

Change to

<pre>
var x:int=e.x - e.originX - _camera.x * e.graphic.scrollX, 
    y:int=e.y - e.originY - _camera.y * e.graphic.scrollY;
</pre>

# 

Open

<pre>
package net.flashpunk.debug.Console
</pre>

Find in function renderEntities

<pre>
g.drawRect((e.x - e.originX - FP.camera.x) * sx, (e.y - e.originY - FP.camera.y) * sy, e.width * sx, e.height * sy);</pre>

Change to

<pre>
g.drawRect((e.x - e.originX - FP.camera.x * e.graphic.scrollX) * sx, (e.y - e.originY - FP.camera.y * e.graphic.scrollY) * sy, e.width * sx, e.height * sy);</pre>

**Comment by Draknek** [comment]
`scrollX` and `scrollY` are intended for graphical entities, you probably shouldn't be using them on an entity which has a hitbox.

The position of a hitbox is not affected by a graphic's `scrollX` and `scrollY` properties. This change might render them where you'd expect, but the physical hitbox the code uses would be somewhere else.

**Comment by tmh** [comment]
:D. Got it.
