### ISSUE TITLE
Update Sequence

### ISSUE THREAD

**Issue by kevinresol** [useflashpunk/FlashPunk#47]
it is possible to have a function like bringToFront / sendToBack for the updateFirst, updateNext sequence? Because some entity would want to update in advance of other entities. It is particularly useful for building UI where some input would have higher priority when being handled.

**Comment by Draknek** [comment]
Relying on the entity update order is rather hacky so I don't think this is the kind of thing I want to encourage.

What I generally do is override `World.update` and do some processing before/after calling `super.update()`

**Comment by kevinresol** [comment]
Really? But I can foresee tons of conditioning statements in the World.update() function just to ensure some entities are updated first.

I just think it would be easier to get the job done by arranging the update sequence. However, I understand that arranging the update sequence would be a little bit difficult as the arrangement has to be stored until the end of a frame where the sequence can be actually changed. 

Thanks for the advice anyway!

**Comment by Draknek** [comment]
Well I probably would want code that needs to be run first to not be in any entity at all: it would be at world-level.

Note that you do have some basic control over the ordering by which order you add them to the world however.

Closing the issue as WONTFIX (though feel free to continue discussing it)
