### ISSUE TITLE
VCR-style Game Replay/Record feature

### ISSUE THREAD

**Issue by azrafe7** [useflashpunk/FlashPunk#91]
Just poked a bit with Flixel and found out it has a nice feature for recording/playing games (by saving/loading mouse and keyboard input - so not that precise, but quite acceptable).

It would surely be of great help for making "beat your shadow" games (and not only: see Bullet Time Ninja).

Just wondering what you guys think about implementing it for FlashPunk. Any thoughts?

**Comment by zachwlewis** [comment]
I don't think this is a core feature, but it should be totally possible. I'd approach it by creating a recording class that you can start, stop and replay. Once started, you can record inputs, and they are saved in a list with the input and the time since recording started.

To replay, you iterate on that list, performing each action as its time step is reached.

**Comment by azrafe7** [comment]
Yes, I seem to remember that Flixel implements it that way - more or less. 

But what is missing, if you're going the same way with FlashPunk, is a bunch of core functions to _simulate_ input when replaying back.

Also: an unwanted side-effect of this approach (which I experienced playing some Flixel games) is that the main player's input must be disabled when the shadow is playing to avoid to apply it to both. Not sure how to work around that.

**Comment by zachwlewis** [comment]
You just feed the input into an entity. You won't have to worry about input conflicts at all.
—

**Comment by azrafe7** [comment]
Well, it's not that simple in my view: there's no way to redirect the input to a single Entity (at the moment).

Maybe you're talking about sampling/registering the Entity's state at fixed/variable intervals. But, if that's the case, all sort of properties (also deep down the hierarchy) must be recorded (graphic visibility, angle, curr animation, etc.). Basically implement serialization in FP.

Furthermore one must ensure that the game is fairly deterministic (an enemy should not spawn at a random position when you replay, but where it was previously).

**Comment by Draknek** [comment]
This is really not the kind of feature that it makes sense to implement within FlashPunk.

I'm going to mark this issue as closed because of that, but do please feel free to continue discussing it here. (Or move the discussion to the forum?)

**Comment by azrafe7** [comment]
I agree it should not be a core functionality. Just wanted to open a discussion and find out how others would implement it.

As a side note I'd wish to point out that having a way to simulate input could be a benefit in multiple situations (first things that come to mind: in-game tutorials and main menu background demos). Sure, not top priority, but handful to have!

**Comment by zachwlewis** [comment]
@azrafe7 I've started a thread on the FlashPunk developers forum that discusses this topic.
- [Input-based Recording & Playback](http://developers.useflashpunk.net/t/input-based-recording-playback/261)
