### ISSUE TITLE
Switching from World A->B->A within the same frame causes switch to World B

### ISSUE THREAD

**Issue by bvance** [useflashpunk/FlashPunk#96]
An edge case exists in the setter for the FP class' world parameter wherein assigning a new World and then reassigning the current World within the same frame will result in a switch to the new one rather than the current (and most recently assigned) one.

This is the setter function as it currently is:

`public static function set world(value:World):void
{
    if (_world == value) return;
    _goto = value;
}`

Suppose you are currently in `worldA`. If you were to write:

`FP.world = worldB;
FP.world = worldA;`

FlashPunk would switch to `worldB` at the end of the frame rather than remaining on `worldA` (because, in that case, `_world` is equal to `value`). This is a confusing behavior; I believe FlashPunk should instead compare `value` against `_goto` in preference to comparing it against `_world` like so:

`public static function set world(value:World):void
{
    if ((_goto ? _goto : _world) == value) return;
    _goto = value;
}`

This way FlashPunk will always select the most recently assigned World at the end of each frame.

**Comment by SmartKid** [comment]
https://github.com/SmartKid/FlashPunk/commit/bfd3e6af1aa2676e6f5a4b34f957b7fa3a471995

**Comment by AbelToy** [comment]
bump.
